apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  EUREKA_URL: "http://eureka-server:8761/eureka/"
  CONFIG_SERVER_URL: "optional:configserver:http://config-server:8888"
  ZIPKIN_URL: "http://zipkin:9411/api/v2/spans"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
