apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:
  # This is the key the 'core-db' pod is dying for:
  MYSQL_ROOT_PASSWORD: "root123"
  # These are for your other services:
  DB_USERNAME: "root"
  JWT_SECRET: "mySecretKey12345678901234567890123456789012345678"
  RABBITMQ_USERNAME: "guest"
  RABBITMQ_PASSWORD: "guest"