server:
  port: 8081

spring:
  application:
    name: auth-service
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

jwt:
  secret: "mySecretKey12345678901234567890123456789012345678"
  expiration: 86400000

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

---
# --- KUBERNETES / DOCKER (Default) ---
spring:
  config:
    activate:
      on-profile: default
    import: "optional:configserver:http://config-server:8888"
  datasource:
    url: jdbc:mysql://auth-db:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

---
# --- LOCAL DEVELOPMENT ---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  zipkin:
    tracing:
      enabled: false