# Server
server.port=8080

# MySQL Database
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=rwUFulKaYOifDpDtDbjGyWHrNpkWbQqD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=${JWT_SECRET:mySecretKeyForJWTAuthThatIsAtLeast32CharsLong}
jwt.expiration=86400000

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:manojkumarprince01@gmail.com}
spring.mail.password=${MAIL_PASSWORD:ouxyvqgzvzezrguo}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Cloudinary
cloudinary.cloud.name=${CLOUDINARY_CLOUD_NAME:damzybrys}
cloudinary.api.key=${CLOUDINARY_API_KEY:736279585883567}
cloudinary.api.secret=${CLOUDINARY_API_SECRET:mClQcjjX2ju5TdNNeS9UZ9-wffI}

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true