global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'ecommerce-monolith'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ecommerce-service:8080']

  - job_name: 'ai-pricing-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ai-pricing-service:8083']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8084']
